export default function App() { return (<>
<a className="skip" href="#contenido">Saltar al contenido</a>
<header><a className="brand" href="#inicio" aria-label="ML Soluciones Web, inicio"><img src="assets/ml-icon.png" alt="" width="58" height="58" /><span>ML<span className="brand-sub">SOLUCIONES WEB</span></span></a><nav aria-label="Navegación principal"><a href="#servicios">Servicios</a><a href="#trabajos">Trabajos</a><a href="#sobre-mi">Sobre mí</a></nav><a className="button small" href="#contacto">Hablemos</a></header>
<main id="contenido"><section className="hero wrap" id="inicio"><div className="hero-copy"><p className="eyebrow">DISEÑO Y DESARROLLO WEB</p><h1>Tu negocio.<br />Su mejor versión<br /><span>en la web.</span></h1><p className="intro">Páginas web y tiendas online que muestran lo que hacés y hacen más fácil que tus clientes te encuentren y te contacten.</p><div className="actions"><a className="button" href="https://wa.me/5493482679540?text=Hola%20Mat%C3%ADas%2C%20quiero%20consultarte%20por%20una%20web." target="_blank" rel="noopener">Contame tu proyecto</a><a className="text-link" href="#trabajos">Ver mis trabajos</a></div><p className="hero-note">Atención directa con Matías Lavoy · Propuestas a medida</p></div><div className="hero-brand"><span className="frame-label">UNA PRESENCIA QUE TE REPRESENTE</span><img src="assets/ml-logo.png" alt="ML Soluciones Web" width="1536" height="1024" /><div className="brand-caption"><span>Diseño con intención.</span><span>Desarrollo a medida.</span></div></div></section>
<div className="strip"><div className="wrap"><span>LANDING PAGES</span><span>SITIOS INSTITUCIONALES</span><span>TIENDAS ONLINE</span><span>MEJORAS Y SEO</span></div></div>
<section className="wrap section" id="servicios"><div className="section-heading"><div><p className="eyebrow">01 / QUÉ PUEDO HACER POR VOS</p><h2>Una web pensada<br />para tu próximo paso.</h2></div><p>Desde tu primera página hasta una tienda que necesita ordenarse. Partimos de lo que tu negocio necesita.</p></div><div className="services"><article><span className="number">01</span><h3>Landing pages<br />y páginas web</h3><p>Presentá tu negocio, tus servicios o una propuesta puntual con una página clara y adaptada a celulares.</p><ul><li>Diseño alineado con tu marca</li><li>Contacto directo por WhatsApp</li><li>Estructura y contenido organizados</li></ul></article><article><span className="number">02</span><h3>Tiendas online<br />con Tiendanube</h3><p>Una tienda organizada para mostrar tus productos y acompañar a tus clientes desde la primera visita.</p><ul><li>Configuración y personalización</li><li>Organización de productos y categorías</li><li>Acompañamiento para empezar</li></ul></article><article><span className="number">03</span><h3>Mejoras web<br />y SEO</h3><p>Si ya tenés una web, revisamos qué se puede mejorar para que sea más clara, útil y fácil de encontrar.</p><ul><li>Orden del contenido y la navegación</li><li>Revisión de títulos y descripciones</li><li>Mejoras según las necesidades del sitio</li></ul></article></div></section>
<section className="work-section section" id="trabajos"><div className="wrap"><div className="section-heading"><div><p className="eyebrow">02 / TRABAJOS</p><h2>Proyectos reales.<br />Identidades propias.</h2></div><p>Cada negocio tiene una historia diferente. Mi trabajo es darle una presencia digital que la acompañe.</p></div><div className="projects">
<a className="project" href="https://dermaraiz.com.ar/" target="_blank" rel="noopener"><div className="project-cover derma"><span className="project-domain">dermaraiz.com.ar</span><strong>Dermaraíz<span>Salud y cuidado de la piel</span></strong><span className="project-type">SITIO WEB</span></div><div className="project-info"><h3>Dermaraíz</h3><p>Diseño y desarrollo del sitio web.</p><span className="text-link">Visitar sitio</span></div></a>
<a className="project" href="https://tomentocapilar.com.ar/" target="_blank" rel="noopener"><div className="project-cover tomento"><span className="project-domain">tomentocapilar.com.ar</span><strong>TOMENTO<span>CAPILAR</span></strong><span className="project-type">SITIO WEB</span></div><div className="project-info"><h3>Tomento Capilar</h3><p>Diseño y desarrollo del sitio web.</p><span className="text-link">Visitar sitio</span></div></a>
<a className="project" href="https://lopezleonindumentaria.com.ar/" target="_blank" rel="noopener"><div className="project-cover lopez"><span className="project-domain">lopezleonindumentaria.com.ar</span><strong>LÓPEZ LEÓN<span>INDUMENTARIA</span></strong><span className="project-type">TIENDANUBE · MEJORAS EN CURSO</span></div><div className="project-info"><h3>López León</h3><p>Organización de la tienda y mejoras de SEO en curso.</p><span className="text-link">Visitar tienda</span></div></a>
</div></div></section>
<section className="wrap section about" id="sobre-mi"><div><p className="eyebrow">03 / QUIÉN ESTÁ DETRÁS</p><h2>Hola, soy Matías.<br /><span>Hablemos de tu idea.</span></h2></div><div className="about-copy"><p>Detrás de ML Soluciones Web estoy yo, Matías Lavoy. Diseño y desarrollo sitios para negocios que quieren dar su próximo paso en internet.</p><p>Vas a hablar directamente conmigo: desde la primera idea hasta la puesta online. La propuesta parte de entender qué hacés, a quién querés llegar y qué necesitás que tu web resuelva.</p><a className="text-link" href="#contacto">Empecemos por una conversación</a></div></section>
<section className="wrap section process"><div className="section-heading"><div><p className="eyebrow">04 / CÓMO TRABAJAMOS</p><h2>De la idea a tu web.</h2></div></div><div className="steps"><article><span>01 / CONVERSAMOS</span><h3>Conozco tu negocio</h3><p>Me contás tu idea, tus objetivos y qué necesitás.</p></article><article><span>02 / DEFINIMOS</span><h3>Una propuesta clara</h3><p>Acordamos alcance, presupuesto y tiempos antes de empezar.</p></article><article><span>03 / CREAMOS</span><h3>Le damos forma</h3><p>Trabajo en el diseño y el desarrollo, y revisamos los avances juntos.</p></article><article><span>04 / PUBLICAMOS</span><h3>Tu sitio, online</h3><p>Revisamos la versión final y conectamos la web con tu dominio.</p></article></div></section>
<section className="contact wrap" id="contacto"><p className="eyebrow">EL PRÓXIMO PROYECTO PUEDE SER EL TUYO</p><h2>Hagamos lugar<br />a tu negocio <span>online.</span></h2><p>Contame qué tenés en mente. Vemos juntos por dónde empezar.</p><a className="button light" href="https://wa.me/5493482679540?text=Hola%20Mat%C3%ADas%2C%20quiero%20consultarte%20por%20una%20web." target="_blank" rel="noopener">Hablemos por WhatsApp</a><a className="email" href="mailto:mlsolucioneswebar@gmail.com">mlsolucioneswebar@gmail.com</a></section></main>
<footer className="wrap"><a className="brand" href="#inicio"><img src="assets/ml-icon.png" alt="" width="46" height="46" /><span>ML Soluciones Web</span></a><p>Matías Lavoy · Diseño y desarrollo web</p><span>© 2026</span></footer>
</>); }
