import { useEffect, useState } from 'react';

function ServiceIcon({type}) { return <svg viewBox="0 0 32 32" width="32" height="32" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{type===0 ? <><rect x="3" y="5" width="26" height="22" rx="3"/><path d="M3 12h26M8 8.5h.1M12 8.5h.1M9 18h7M9 22h13"/></> : type===1 ? <><path d="M6 12h20l2 16H4l2-16Z"/><path d="M11 13V9a5 5 0 0 1 10 0v4"/></> : <><circle cx="14" cy="14" r="9"/><path d="m21 21 8 8M9 17l4-5 4 3 3-5"/></>}</svg>; }

function ContactForm() {
  const [ready, setReady] = useState('');
  function prepare(event) {
    event.preventDefault();
    const data = new FormData(event.currentTarget);
    const name = String(data.get('name')).trim();
    const message = String(data.get('message')).trim();
    if (!name || !message) return;
    const text = ['Hola Matías, soy ' + name + '.', 'Negocio: ' + (String(data.get('business')).trim() || 'Por definir'), 'Email: ' + String(data.get('email')).trim(), 'Me interesa: ' + data.get('service'), '', message].join('\n');
    setReady('https://wa.me/5493482679540?text=' + encodeURIComponent(text));
  }
  return <form className="inquiry-form" onSubmit={prepare} onChange={() => setReady('')}>
    <div className="form-heading"><span>CONTAME TU IDEA</span><p>Empecemos por conocernos.</p></div>
    <div className="form-row"><label>Tu nombre<input name="name" autoComplete="name" required maxLength={100} placeholder="¿Cómo te llamás?" /></label><label><span className="field-title">Tu negocio <small>(opcional)</small></span><input name="business" autoComplete="organization" maxLength={120} placeholder="Nombre de tu marca" /></label></div>
    <label>Email<input name="email" type="email" autoComplete="email" required maxLength={160} placeholder="vos@ejemplo.com" /></label>
    <label>¿Qué necesitás?<select name="service" required defaultValue=""><option value="" disabled>Elegí una opción</option><option>Página web o landing page</option><option>Tienda online</option><option>Mejoras web y SEO</option><option>Necesito orientación</option></select></label>
    <label>Un poco sobre tu proyecto<textarea name="message" required minLength={10} maxLength={2000} rows={4} placeholder="Qué hacés, qué te gustaría lograr y si ya tenés una web..." /></label>
    <button className="button" type="submit">Preparar mi consulta</button>
    <p className="form-note">Armamos tu mensaje para WhatsApp. Vos lo revisás y lo enviás desde allí. Estos datos no se guardan en la página.</p>
    <div aria-live="polite">{ready && <div className="form-ready"><p>Tu consulta está lista. Abrí WhatsApp para revisarla y enviarla.</p><a className="button" href={ready} target="_blank" rel="noopener noreferrer">Abrir WhatsApp y continuar</a></div>}</div>
  </form>;
}

export default function App() {
  useEffect(() => {
    if (window.matchMedia('(prefers-reduced-motion: reduce)').matches || !('IntersectionObserver' in window)) return;
    const nodes = document.querySelectorAll('.section-heading, .services article, .project, .about > div, .steps article, .contact-copy, .inquiry-form');
    const observer = new IntersectionObserver(entries => entries.forEach(entry => {
      if (entry.isIntersecting) { entry.target.classList.add('revealed'); observer.unobserve(entry.target); }
    }), { threshold: 0.08 });
    nodes.forEach(node => { node.classList.add('reveal'); observer.observe(node); });
    return () => { observer.disconnect(); nodes.forEach(node => node.classList.remove('reveal')); };
  }, []);
  return (<>
<a className="skip" href="#contenido">Saltar al contenido</a>
<header><a className="brand" href="#inicio" aria-label="ML Soluciones Web, inicio"><img src="assets/ml-icon.png" alt="" width="58" height="58" /><span>ML<span className="brand-sub">SOLUCIONES WEB</span></span></a><nav aria-label="Navegación principal"><a href="#servicios">Servicios</a><a href="#trabajos">Trabajos</a><a href="#sobre-mi">Sobre mí</a></nav><a className="button small" href="#contacto">Hablemos</a></header>
<main id="contenido"><section className="hero wrap" id="inicio"><div className="hero-copy"><p className="eyebrow">DISEÑO Y DESARROLLO WEB</p><h1>Tu negocio.<br />Su mejor versión<br /><span>en la web.</span></h1><p className="intro">Páginas web y tiendas online que muestran lo que hacés y hacen más fácil que tus clientes te encuentren y te contacten.</p><div className="actions"><a className="button" href="https://wa.me/5493482679540?text=Hola%20Mat%C3%ADas%2C%20quiero%20consultarte%20por%20una%20web." target="_blank" rel="noopener">Contame tu proyecto</a><a className="text-link" href="#trabajos">Ver mis trabajos</a></div><p className="hero-note">Atención directa con Matías Lavoy · Propuestas a medida</p></div><div className="hero-visual"><div className="hero-photo"><img src="/assets/development.jpg" alt="Notebook con un proyecto de desarrollo web en pantalla" width="1200" height="799" fetchPriority="high" /><div className="photo-caption"><span>DE LA IDEA A LA PANTALLA</span><p>Una web que se sienta<br /><strong>tan tuya como tu negocio.</strong></p></div></div><div className="hero-detail"><span className="detail-symbol" aria-hidden="true">✳</span><div><strong>Hecha para tu negocio</strong><span>Diseño, desarrollo y atención personal.</span></div></div></div></section>
<div className="strip"><div className="wrap"><span>LANDING PAGES</span><span>SITIOS INSTITUCIONALES</span><span>TIENDAS ONLINE</span><span>MEJORAS Y SEO</span></div></div>
<section className="wrap section" id="servicios"><div className="section-heading"><div><p className="eyebrow">01 / QUÉ PUEDO HACER POR VOS</p><h2>¿Qué necesita<br />hoy tu negocio?</h2></div><p>Mostrar tus servicios, vender online o mejorar tu sitio actual. Encontramos la solución que tenga sentido para vos.</p></div><div className="services"><article><div className="service-top"><span className="service-icon"><ServiceIcon type={0} /></span><span className="number">01</span></div><span className="service-purpose">PRESENTÁ TU NEGOCIO</span><h3>Landing pages<br />y páginas web</h3><p>Presentá tu negocio, tus servicios o una propuesta puntual con una página clara y adaptada a celulares.</p><ul><li>Diseño alineado con tu marca</li><li>Contacto directo por WhatsApp</li><li>Estructura y contenido organizados</li></ul></article><article><div className="service-top"><span className="service-icon"><ServiceIcon type={1} /></span><span className="number">02</span></div><span className="service-purpose">VENDÉ TUS PRODUCTOS</span><h3>Tiendas online<br />con Tiendanube</h3><p>Una tienda organizada para mostrar tus productos y acompañar a tus clientes desde la primera visita.</p><ul><li>Configuración y personalización</li><li>Organización de productos y categorías</li><li>Acompañamiento para empezar</li></ul></article><article><div className="service-top"><span className="service-icon"><ServiceIcon type={2} /></span><span className="number">03</span></div><span className="service-purpose">MEJORÁ LO QUE YA TENÉS</span><h3>Mejoras web<br />y SEO</h3><p>Si ya tenés una web, revisamos qué se puede mejorar para que sea más clara, útil y fácil de encontrar.</p><ul><li>Orden del contenido y la navegación</li><li>Revisión de títulos y descripciones</li><li>Mejoras según las necesidades del sitio</li></ul></article></div></section>
<section className="work-section section" id="trabajos"><div className="wrap"><div className="section-heading"><div><p className="eyebrow">02 / TRABAJOS</p><h2>Proyectos reales.<br />Identidades propias.</h2></div><p>Cada negocio tiene una historia diferente. Mi trabajo es darle una presencia digital que la acompañe.</p></div><div className="projects">
<a className="project" href="https://dermaraiz.com.ar/" target="_blank" rel="noopener"><div className="project-cover derma"><span className="project-domain">dermaraiz.com.ar</span><img className="client-logo derma-logo" src="/assets/dermaraiz.svg" alt="Logo de Dermaraíz" loading="lazy" width="220" height="160" /><span className="project-type">SITIO WEB</span></div><div className="project-info"><h3>Dermaraíz</h3><p>Diseño y desarrollo del sitio web.</p><span className="text-link">Visitar sitio</span></div></a>
<a className="project" href="https://tomentocapilar.com.ar/" target="_blank" rel="noopener"><div className="project-cover tomento"><span className="project-domain">tomentocapilar.com.ar</span><img className="client-logo" src="/assets/tomento.png" alt="Logo de Tomento Capilar" loading="lazy" width="280" height="198" /><span className="project-type">SITIO WEB</span></div><div className="project-info"><h3>Tomento Capilar</h3><p>Diseño y desarrollo del sitio web.</p><span className="text-link">Visitar sitio</span></div></a>
<a className="project" href="https://lopezleonindumentaria.com.ar/" target="_blank" rel="noopener"><div className="project-cover lopez"><span className="project-domain">lopezleonindumentaria.com.ar</span><img className="client-logo" src="/assets/lopez-leon.webp" alt="Logo de López León" loading="lazy" width="360" height="90" /><span className="project-type">TIENDANUBE · MEJORAS EN CURSO</span></div><div className="project-info"><h3>López León</h3><p>Organización de la tienda y mejoras de SEO en curso.</p><span className="text-link">Visitar tienda</span></div></a>
</div></div></section>
<section className="wrap section about" id="sobre-mi"><div><p className="eyebrow">03 / QUIÉN ESTÁ DETRÁS</p><h2>Hola, soy Matías.<br /><span>Hablemos de tu idea.</span></h2></div><div className="about-copy"><p>Soy Matías Lavoy. Creé ML Soluciones Web para ayudar a negocios y profesionales a mostrar lo que hacen con una web clara, cuidada y fácil de usar.</p><p>Me involucro en cada etapa: escucho tu idea, te propongo un camino y me encargo del diseño y el desarrollo. Revisamos los avances juntos, con explicaciones simples y acuerdos claros desde el principio.</p><a className="text-link" href="#contacto">Contame qué querés construir</a></div></section>
<section className="wrap section process" id="proceso"><div className="section-heading"><div><p className="eyebrow">04 / CÓMO TRABAJAMOS</p><h2>De la idea a tu web.</h2></div></div><div className="steps"><article><div className="step-photo"><img src="/assets/process-conversation.jpg" alt="Personas conversando alrededor de una mesa de trabajo" loading="lazy" width="600" height="400" /></div><span>01 / CONVERSAMOS</span><h3>Conozco tu negocio</h3><p>Me contás tu idea, tus objetivos y qué necesitás.</p></article><article><div className="step-photo"><img src="/assets/process-plan.jpg" alt="Manos revisando documentos y anotaciones para acordar una propuesta" loading="lazy" width="600" height="400" /></div><span>02 / DEFINIMOS</span><h3>Una propuesta clara</h3><p>Acordamos alcance, presupuesto y tiempos antes de empezar.</p></article><article><div className="step-photo"><img src="/assets/process-design.jpg" alt="Vista de una mesa donde se trabaja con bocetos, documentos y dispositivos" loading="lazy" width="600" height="400" /></div><span>03 / CREAMOS</span><h3>Le damos forma</h3><p>Trabajo en el diseño y el desarrollo, y revisamos los avances juntos.</p></article><article><div className="step-photo"><img src="/assets/process-launch.jpg" alt="Personas revisando juntas el resultado en una computadora" loading="lazy" width="600" height="400" /></div><span>04 / PUBLICAMOS</span><h3>Tu sitio, online</h3><p>Revisamos la versión final y conectamos la web con tu dominio.</p></article></div></section>
<section className="contact wrap" id="contacto"><div className="contact-copy"><p className="eyebrow">05 / HABLEMOS DE TU PROYECTO</p><h2>Tu próxima web<br />empieza con<br /><span>una buena charla.</span></h2><p>No hace falta que tengas todo resuelto. Contame tu idea y vemos juntos cómo llevarla a la web.</p><div className="contact-method"><span>¿PREFERÍS ESCRIBIRME DIRECTAMENTE?</span><a href="https://wa.me/5493482679540" target="_blank" rel="noopener noreferrer">+54 9 3482 679540</a><a href="mailto:mlsolucioneswebar@gmail.com">mlsolucioneswebar@gmail.com</a></div><p className="personal-note">Vas a hablar conmigo, Matías. Sin intermediarios.</p></div><ContactForm /></section></main>
<footer className="site-footer"><div className="wrap footer-grid"><div className="footer-brand"><a className="brand" href="#inicio"><img src="/assets/ml-icon.png" alt="" width="64" height="64" /><span>ML<span className="brand-sub">SOLUCIONES WEB</span></span></a><p>Diseño y desarrollo web.<br />Tu negocio, con una presencia propia.</p></div><div><h3>Explorá</h3><nav aria-label="Navegación del pie"><a href="#servicios">Servicios</a><a href="#trabajos">Trabajos</a><a href="#sobre-mi">Sobre mí</a><a href="#proceso">Cómo trabajamos</a></nav></div><div><h3>Hagamos algo juntos</h3><a href="mailto:mlsolucioneswebar@gmail.com">mlsolucioneswebar@gmail.com</a><a href="https://wa.me/5493482679540" target="_blank" rel="noopener noreferrer">WhatsApp · +54 9 3482 679540</a><a className="text-link" href="#contacto">Contame tu proyecto</a></div></div><div className="wrap footer-bottom"><span>© {new Date().getFullYear()} ML Soluciones Web · Matías Lavoy</span><a href="#inicio">Volver al inicio</a></div></footer>
</>); }
